added docker config

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -24,10 +24,22 @@ jobs:
       - name: Run health check !
         id: vars
         run: |
-          echo "docker_tag=200" >> $GITHUB_OUTPUT
+          URL="http://stackoverflow.com/"
 
-      - name: Check Status
-        if: ${{ steps.vars.outputs.docker_tag }} != "200"
-        run: |
-          echo ${{ steps.vars.outputs.docker_tag }}
-          exit 1
+# store the whole response with the status at the and
+          HTTP_RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" -X POST $URL)
+          
+          # extract the body
+          HTTP_BODY=$(echo $HTTP_RESPONSE | sed -e 's/HTTPSTATUS\:.*//g')
+          
+          # extract the status
+          HTTP_STATUS=$(echo $HTTP_RESPONSE | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
+          
+          # print the body
+          echo "$HTTP_BODY"
+          
+          # example using the status
+          if [ ! $HTTP_STATUS -eq 200  ]; then
+            echo "Error [HTTP status: $HTTP_STATUS]"
+            exit 1
+          fi
